<a href="https://colab.research.google.com/github/np03cs4s250053-sketch/5CS037/blob/main/Worksheet_1_shreya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem-1: Array Creation:
1. Initialize an empty array with size 2X2.

In [2]:
import numpy as np
a=np.empty((2,2))
print(a)

[[8.72747897e-316 0.00000000e+000]
 [4.94065646e-324 6.92918000e-310]]


2. Initialize an all one array with size 4X2.

In [5]:
a=np.ones((1,1))
print(a)

[[1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [6]:
a=np.full((4,2),15)
print(a)

[[15 15]
 [15 15]
 [15 15]
 [15 15]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [7]:
a=np.array([[5,8,9],[7,6,8]])
new_a=np.zeros_like(a)
print(new_a)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [8]:
a=np.array([[8,5,6],[8,5,4]])
new_ar=np.ones_like(a)
print(new_ar)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [9]:
new_list=[4,5,6,7]
a=np.array(new_list)
print(a)

[4 5 6 7]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [11]:
import numpy as np
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_a=np.random.random(30)
print(random_a)
print("mean: ", random_a.mean())

[0.87018837 0.62416065 0.66227387 0.75825243 0.01468946 0.95931717
 0.62632243 0.86440785 0.8521454  0.2404129  0.79538116 0.33671168
 0.1221149  0.89218161 0.61483039 0.99935621 0.09742282 0.23299667
 0.11976226 0.54154938 0.3336811  0.1673168  0.04977129 0.05029272
 0.79674255 0.72358446 0.03559235 0.75177858 0.31377538 0.72212099]
mean:  0.5056377949896953


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
a=np.random.random((10,10))
print(a)
print("minimum: ", a.min())
print("maximum: ", a.max())

[[0.21618982 0.47501535 0.06745213 0.88082195 0.95223986 0.36769499
  0.34305512 0.52757352 0.72987728 0.84507315]
 [0.36621525 0.72176365 0.40418965 0.24551517 0.18362813 0.74392298
  0.23691411 0.26229537 0.4577732  0.47066311]
 [0.15903141 0.89743602 0.06408757 0.53181957 0.26820544 0.96042862
  0.90902333 0.0417377  0.94748198 0.62371812]
 [0.39200346 0.83675819 0.56525131 0.70156299 0.35176243 0.52748159
  0.10910933 0.85911951 0.74297068 0.86321673]
 [0.04574657 0.81092795 0.92568653 0.63467753 0.29655949 0.76505529
  0.53609577 0.56831013 0.9903791  0.68228337]
 [0.286959   0.37038033 0.24004    0.55656381 0.18374357 0.93089091
  0.53152565 0.2363228  0.85050917 0.09380857]
 [0.54937167 0.0448028  0.7061306  0.4062717  0.66952941 0.99922251
  0.85502925 0.75327257 0.58880765 0.83617835]
 [0.19837411 0.03742127 0.22998438 0.94040169 0.94830175 0.69582627
  0.31507608 0.56847773 0.24668219 0.730571  ]
 [0.75664191 0.99330894 0.25268616 0.32095277 0.50057035 0.38668499
  0.64164412

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
a=np.array([ 1,2,0,0,4,0])
reverse_array=a[::-1]
print("reversed array:", reverse_array)

reversed array: [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2, 1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

1. Add the two array.


In [ ]:
import numpy as np
x= np.array([[1, 2],[3, 5]])
y= np.array([[5, 6],[7, 8]])
v= np.array([9, 10])
w= np.array([11, 12])



2. Subtract the two array.


In [ ]:
add = x + y
print(add)


[[ 6  8]
 [10 13]]



3. Multiply the array with any integers of your choice.


In [ ]:
sub= x - y
print(sub)


[[-4 -4]
 [-4 -3]]



4. Find the square of each element of the array.


In [ ]:
product = 3*x
print(product)


[[ 3  6]
 [ 9 15]]



5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [ ]:
squareofx = x ** 2
print(squareofx)


[[ 1  4]
 [ 9 25]]



6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.}


In [ ]:
dotproduct= np.dot(v, w)
print(dotproduct)


219


In [ ]:
dotproduct = np.dot(x, v)
print(dotproduct)


[29 77]


In [ ]:
dotproduct_xy = np.dot(x, y)
print(dotproduct_xy)


[[19 22]
 [50 58]]


In [ ]:
concatenate_xy = np.vstack((x, y))
print(concatenate_xy)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]



7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
concat_vw = np.column_stack((v, w))
print(concat_vw)


[[ 9 11]
 [10 12]]


Arrays cannot concatenate two arrays of different dimension.So, the error arises when the dimensions are not same.

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A = np.array([[3, 4],[7, 8]])
B = np.array([[5, 3],[2, 1]])


In [ ]:
A_inv = np.linalg.inv(A)
proof1 = np.dot(A, A_inv)
print(proof1)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print(AB)
print(BA)


[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
AB_transpose = (AB).T
BT_AT = np.dot(B.T, A.T)
print(AB_transpose)
print(BT_AT)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
A2 = np.array([[2, -3,  1],[1, -1,  2],[3,  1, -1]])
B2 = np.array([-1, -3, 9])


In [ ]:
A2_inv = np.linalg.inv(A2)
X = np.dot(A2_inv, B2)
print(X)


[ 2.  1. -2.]


In [ ]:
X2 = np.linalg.solve(A2, B2)
print(X2)


[ 2.  1. -2.]


In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

#ADDITION
# Python lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")
# NumPy arrays
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")

#MULTIPLICATION
# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")
# NumPy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")

#DOT PRODUCT
# Python lists
start = time.time()
dot_py = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")
# NumPy arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start, "seconds")

#MATRIX MULTIPLICATION
# Python lists
M1 = [[i for i in range(1000)] for _ in range(1000)]
M2 = [[i for i in range(1000)] for _ in range(1000)]
start = time.time()
# matrix multiplication using python
result_py = [[sum(M1[i][k] * M2[k][j] for k in range(1000))
              for j in range(1000)]
              for i in range(1000)]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy arrays
A = np.arange(1_000_000).reshape(1000, 1000)
B = np.arange(1_000_000).reshape(1000, 1000)
start = time.time()
result_np = np.dot(A, B)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")

Python List Addition Time: 0.10191559791564941 seconds
NumPy Array Addition Time: 0.004437685012817383 seconds
Python List Multiplication Time: 0.10568428039550781 seconds
NumPy Array Multiplication Time: 0.005117177963256836 seconds
Python List Dot Product Time: 0.10431742668151855 seconds
NumPy Dot Product Time: 0.0017592906951904297 seconds
Python List Matrix Multiplication Time: 180.67365264892578 seconds
NumPy Matrix Multiplication Time: 1.314997911453247 seconds
